# Generated by Django 3.1.7 on 2021-04-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=30)),
                ('building_name', models.CharField(max_length=30)),
                ('building_number', models.CharField(max_length=30)),
                ('building_address', models.CharField(max_length=30)),
                ('flat_size', models.CharField(max_length=30)),
                ('num_of_beds', models.CharField(max_length=30)),
                ('num_of_toilet', models.CharField(max_length=30)),
                ('num_of_balcony', models.CharField(max_length=30)),
                ('map_address', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('home_address', models.CharField(max_length=500)),
                ('police_station', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourproject.user')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_bill', models.CharField(max_length=30)),
                ('bill_number', models.CharField(max_length=50)),
                ('paid_amount', models.CharField(max_length=30)),
                ('bill_month', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourproject.user')),
            ],
        ),
    ]
